CREATE DATABASE DEVELOPERS;
USE DEVELOPERS;
CREATE TABLE EMPLOYEE_DETAILS(
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR(100),
DEPARTMENT VARCHAR(100),
SALARY int,
CITY varchar(20)
);
SELECT * FROM employee_details;
INSERT INTO employee_details(NAME,DEPARTMENT,SALARY,CITY) VALUES ("AK","SOFTWARE DEVELOPER",20000,"CHENNAI"),("ABI","SENIOR ANALYST TRAINEE",30000,"MADURAI"),("GIRI","FULL STACK DEVELOPER",40000,"CHENNAI");
INSERT INTO employee_details(NAME,DEPARTMENT,SALARY,CITY) VALUES ("HARISH","CYBER SECURITY",25000,"TENKASI"),("SUNDAR","DATA SCIENCE ENGINEER",32000,"BANGALORE"),("ARUN","FRONTEND DEVELOPER",40000,"CHENNAI");
INSERT INTO employee_details(NAME,DEPARTMENT,SALARY,CITY) VALUES ("SK","CYBERSECURITY ENGINNER",42000,"PUNE"),("JEEVA","DEVOPS ENGINNER",30000,"TENKASI"),("PRABU","SOFTWARE DEVELOPER",40000,"CHENNAI"),("BALA","FRONTEND DEVELOPER",40000,"CHENNAI");
SELECT * FROM EMPLOYEE_DETAILS;
SELECT DEPARTMENT, count(*) FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT DEPARTMENT , avg(SALARY) FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE_DETAILS;
SELECT CITY, count(*)  AS TOTALCOUNT FROM EMPLOYEE_DETAILS GROUP BY CITY;
SELECT DEPARTMENT, min(salary) as MINIMUMSALARY, max(salary) AS MAXIMUMSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE_DETAILS;
SELECT DEPARTMENT, min(salary) as MINIMUMSALARY, max(salary) AS MAXIMUMSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE_DETAILS;
SELECT DEPARTMENT, min(salary) as MINIMUMSALARY, max(salary) AS MAXIMUMSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT DEPARTMENT, sum(SALARY)  AS TOTALSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT DEPARTMENT , COUNT(*) AS TOTALEMPLOYEE FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING COUNT(*) >2;
SELECT DEPARTMENT , AVG(SALARY) AS AVERAGESALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING AVG(SALARY)<= 50000;
SELECT CITY, COUNT(*) AS TOTALEMPLOYEE FROM EMPLOYEE_DETAILS GROUP BY CITY  HAVING COUNT(*) >2;
SELECT DEPARTMENT, MAX(SALARY) AS TOTALSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING MAX(SALARY) >70000;
SELECT DEPARTMENT,  SUM(SALARY) AS TOTALSALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING SUM(SALARY) >=40000;
SELECT DEPARTMENT , AVG(SALARY) AS AVERAGESALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING AVG(SALARY) >(SELECT AVG(SALARY) FROM EMPLOYEE_DETAILS);
SELECT CITY, AVG(SALARY) AS AVERAGESALARY FROM EMPLOYEE_DETAILS GROUP BY CITY HAVING AVG(SALARY) >35000;
SELECT DEPARTMENT, COUNT(*) AS TOATLEMPLOYEE FROM EMPLOYEE_DETAILS WHERE SALARY >35000 GROUP BY DEPARTMENT ;
SELECT DEPARTMENT, COUNT(*) AS TOTALEMPLOYEE  FROM EMPLOYEE_DETAILS  GROUP BY DEPARTMENT HAVING MIN(SALARY) > 40000;

USE DEVELOPERS;
SELECT DEPARTMENT, AVG(SALARY) AS AVERAGESALARY FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE_DETAILS;

SELECT NAME, lower(NAME) FROM EMPLOYEE_DETAILS;
SELECT * FROM EMPLOYEE_DETAILS;

SELECT CITY, COUNT(*) FROM EMPLOYEE_DETAILS GROUP BY CITY;
SELECT * FROM EMPLOYEE_DETAILS;

SELECT DEPARTMENT , AVG(SALARY) FROM EMPLOYEE_DETAILS GROUP BY DEPARTMENT HAVING AVG(SALARY)<50000;
SELECT NAME, length(NAME) FROM EMPLOYEE_DETAILS GROUP BY NAME HAVING LENGTH(NAME)>5;

SELECT * FROM EMPLOYEE_DETAILS;
SELECT REPLACE(NAME,'A','@') AS MODIFIEDDATA FROM EMPLOYEE_DETAILS;

SELECT * FROM EMPLOYEE_DETAILS;
SELECT CITY, MAX(SALARY) AS HIGHESTSALARY FROM EMPLOYEE_DETAILS GROUP BY CITY;
